language: python
cache: 
  - pip

services:
  - docker

before_install:
  - docker build -t miriam .
  - docker run miriam

python:
  - "3.6"

install:
 - pip install -r requirements.txt

script:
  - py.test -vs
