language: python
python:
  - "3.5"
  - "3.5"

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - sudo apt-get install python-qt4

# command to run tests
script: py.test -vs